export const RETRIEVE_ALBUMS = "RETRIEVE_ALBUMS";
export const ALBUMS_ERROR = "ALBUM_ERROR";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LAST_ALBUM_RETRIEVED = "LAST_ALBUM_RETRIEVED";
export const STORE_ACCESS_TOKEN = "STORE_ACCESS_TOKEN";
